name: ShuttleHQ deploy
description: "Deploy to shuttle"

inputs:
  deploy-key:
    description: 'the key found at "https://www.shuttle.rs/login"'
    required: true
  working-directory:
    description: "the directory which includes the `Cargo.toml`"
    required: false
    default: "."
  allow-dirty:
    description: "allow uncommitted changes to be deployed"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - id: check-repo-is-not-initialized
      run: echo "remote-url=$( git config --get remote.origin.url )" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/checkout@v3
      if: ${{ !contains(steps.check-repo-is-not-initialized.outputs.remote-url, github.repository) }}
    - name: Install shuttle cli
      run: |
        # using cargo-binstall because it is faster to get shuttle-cli binary
        cargo install cargo-binstall
        cargo binstall -y cargo-shuttle
      shell: bash
    - name: Log into shuttle
      run: cargo shuttle login --api-key ${{ inputs.deploy-key }}
      shell: bash
    - name: Deploy to shuttle
      if: ${{ inputs.allow-dirty == 'false' }}
      run: cargo shuttle deploy | awk '!/Database URI.*?$/'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - name: Deploy to shuttle
      if: ${{ inputs.allow-dirty != 'false' }}
      run: cargo shuttle deploy --allow-dirty | awk '!/Database URI.*?$/'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
