name: ShuttleHQ deploy
description: "Deploy to shuttle"

inputs:
  deploy-key:
    description: 'the key found at "https://www.shuttle.rs/login"'
    required: true
  working-directory:
    description: "the directory which includes the `Cargo.toml`"
    required: false
    default: "."
  allow-dirty:
    description: "allow uncommitted changes to be deployed"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
      # check out repo if not done already
    - id: check-repo-is-not-initialized
      run: echo "remote-url=$( git config --get remote.origin.url )" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/checkout@v3
      if: ${{ !contains(steps.check-repo-is-not-initialized.outputs.remote-url, github.repository) }}

      # using cargo-binstall because it is faster to get shuttle-cli binary
    - name: Install cargo-binstall
      run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - name: Install cargo-shuttle
      run: cargo binstall -y cargo-shuttle

    - name: Deploy to shuttle
      if: ${{ inputs.allow-dirty == 'false' }}
      run: cargo shuttle deploy | awk '!/Database URI.*?$/'
      working-directory: ${{ inputs.working-directory }}
      env:
        SHUTTLE_API_KEY: ${{ inputs.deploy-key }}
    - name: Deploy to shuttle
      if: ${{ inputs.allow-dirty != 'false' }}
      run: cargo shuttle deploy --allow-dirty | awk '!/Database URI.*?$/'
      working-directory: ${{ inputs.working-directory }}
      env:
        SHUTTLE_API_KEY: ${{ inputs.deploy-key }}
